server:
  port: 7824
spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 10 # 最大连接数
#        max-wait: -1ms # 最大等待时间
#        max-idle: 100 # 最大空闲时间
#        min-idle: 0 # 最小空闲时间
  datasource:
    url: jdbc:postgresql://localhost:5432/application-template
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  mail:
    # 配置 SMTP 服务器地址 qq为smtp.qq.com 网易126为smtp.126.com
    host: smtp.126.com
    # 邮箱账号
    username: guetzyf@126.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    # qq邮箱SMTP token :cehuhxhytyxkbjej
    # guetzyf@126.com网易邮箱SMTP token :FSWXIOHOKLKUVVEE
    password: FSWXIOHOKLKUVVEE
    # qq邮箱端口号465或587, 126网易邮箱为25
    port: 25
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
mybatis-plus:
  mapper-locations: classpath:mapperXML/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
